### ISSUE TITLE
Start/stop time and true area in truth info

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/WFSim#10]
Currently WFsim's 'truth info' just repeats the instructions. For testing the processor performance, we instead need for each peak: its actual simulated location in time (e.g. start/stop or left/right) as well as the true number of simulated photons (without afterpulses / single electrons).

See also the truth output production in fax: https://github.com/XENON1T/pax/blob/master/pax/plugins/io/WaveformSimulator.py#L70 and https://github.com/XENON1T/XeAnalysisScripts/blob/master/PeakFinderTest/match_peaks.py, which we used for simulator-based processor tests in XENON1T.

**Comment by petergaemers** [comment]
This is added in pull request #11
