### ISSUE TITLE
Single electron gain

### ISSUE THREAD

**Issue by petergaemers** [XENONnT/WFSim#120]
Currently the single electron gain much too low. 
Instead of being around 40 photons per electron we currently make about 6

This is related to the normalization of the s2 pattern maps not being normalized

**Comment by petergaemers** [comment]
https://github.com/XENONnT/private_nt_aux_files/pull/50
@ramirezdiego @l-althueser

**Comment by ramirezdiego** [comment]
Fixed in https://github.com/XENONnT/private_nt_aux_files/pull/50 and https://github.com/XENONnT/WFSim/pull/143.
