### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by tunnell** [XENONnT/WFSim#139]
If you putting it on PyPI, I'd keep the HISTORY file up to date because otherwise the PyPI page when you are looking for the package only shows really outdated irrelevant info.

**Comment by tunnell** [comment]
Also, see this in setup.py:  'Development Status :: 2 - Pre-Alpha'

**Comment by tunnell** [comment]
Also, this all started with trying to figure out why WFsim versions were appended by a "0." for a student.

**Comment by jorana** [comment]
>, I'd keep the HISTORY 
@tunnell , I agree and made a similar comment/PR:
https://github.com/XENONnT/WFSim/pull/123

**Comment by ramirezdiego** [comment]
Agreed as well. No need for an immediate HISTORY update, but a proper one following #125 (and new release) is planned.

**Comment by jorana** [comment]
With the recent releases and #150 this issue seems solved
