### ISSUE TITLE
Example Kr notebook

### ISSUE THREAD

**Issue by zhut19** [XENONnT/WFSim#166]
The gain calculation bug from #161 and solved in #164, made us realized the importance of having a sanity check notebook. One idea is to simulate Kr events and do simple checks like S1 and S2 area distributions, etc.

**Comment by Jianyu010** [comment]
I placed a sample notebook under ```/project2/lgrandi/jylong/file_delivery/kr83m_wfsim.ipynb```. Can you check whether that's what you want? Thanks.

**Comment by zhut19** [comment]
Resolved in #167
