### ISSUE TITLE
Split and refactor core.py

### ISSUE THREAD

**Issue by terliuk** [XENONnT/WFSim#170]
Our core.py is unreasonably long and very hard to navigate. Does it make sense to split it into separate files corresponding to pulse class, S1, S2 etc? I think it will hugely improve development and testing of our MC.

**Comment by petergaemers** [comment]
Since it's not a lot of work it's fine by me if it helps people

**Comment by zhut19** [comment]
We might want to follow [this](https://devblogs.microsoft.com/oldnewthing/20190916-00/?p=102892) blog?

**Comment by ramirezdiego** [comment]
Are we rescuing this?

**Comment by zhut19** [comment]
We should test this on some other repo first. And since it's not urgent right now, I will put it on hold unless someone else would like to do it.

**Comment by terliuk** [comment]
I would say that advantages of split core is actually more important than having git blame. In the worst case, people can trivially "go" back in time to commits/previous versions and use blame there.
