### ISSUE TITLE
S2 reconstruction bias when using noise (enable_noise)

### ISSUE THREAD

**Issue by dantonmartin** [XENONnT/WFSim#182]
The S2 reconstruction bias seems to be altered by the addition of noise. When using 

`st.set_config(dict(fax_config_override=dict( s2_luminescence_model='simple',enable_noise=1,)))`

, the bias for Ar37-like S2s is in the order of 7%. When enable_noise=0, it is (within statistics) in the order of 0%.
I then re-ran the simulation with slightly higher energies (31.5 keV for Kr83m-like events (no double-S2 though)) and the same effect shows up, although with the bias magnitude being reduced to 2-3%. This points at a constant offset in the area reconstruction, like a wrong baseline. A couple plots showing the effect for Ar37-like.

![image](https://user-images.githubusercontent.com/48393824/124612509-ac1aaf00-de72-11eb-84ec-8b7dbec704ff.png)
![image](https://user-images.githubusercontent.com/48393824/124613559-a6719900-de73-11eb-92aa-3c3504c580b6.png)

I will keep digging and update if I find anything.

**Comment by skazama** [comment]
Thanks @dantonmartin for your careful checks! Maybe I'm wrong, but we also see similar bias in @jorana's study (See[ this fig](https://xe1t-wiki.lngs.infn.it/lib/exe/fetch.php?media=xenon:j_angevaare:rec_bias_compare_lowe_peak_split_gof_th-none0_s1_max_rise_time_-200_s2_merge_max_dura-50000_s1_max_rise_time-110_s2_merge_max_gap-10000.png)). I guess @zhut19 has some ideas to resolve this issue

**Comment by HenningSE** [comment]
Stupid question: The noise file has a mean value of 0?

**Comment by dantonmartin** [comment]
As far as I understand, it doesn't really matter if there is a (small)
offset from 0 as long as the offset is constant, since then strax will
account for the offset during baseline estimation. I will check but Peter G
seems to have found a strange bug regarding baseline construction which
could be the source of the problem.

**Comment by zhut19** [comment]
It turns out to be not a wfsim issue. Fixed with https://github.com/XENONnT/straxen/pull/601
