### ISSUE TITLE
Bug in complex deexcitation model

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/WFSim#77]
With the latest change to move from recoil type string to numbers there was a bug introduced. The check of the input has not been updated: https://github.com/XENONnT/WFSim/blob/26eabfd1093c1c3b0798e84ed96e233124cde156/wfsim/core.py#L328-L332

**Comment by petergaemers** [comment]
Fixed in https://github.com/XENONnT/WFSim/pull/83
